=== fermatupotop/L2J_Mobius_Essence_6.2_Vanguard/game/data/scripts_waytrel/events/GoldenWheel/rewards.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="list">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="params">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="string" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute type="xs:string" name="message" use="optional"/>
                      <xs:attribute type="xs:string" name="Mstring" use="optional"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute type="xs:byte" name="minLevel"/>
            <xs:attribute type="xs:byte" name="maxLevel"/>
            <xs:attribute type="xs:int" name="coinId"/>
          </xs:complexType>
        </xs:element>
        <xs:element type="xs:int" name="multisells">
          <xs:annotation>
            <xs:documentation> maxLevel -1 - no limit </xs:documentation>
          </xs:annotation>
        </xs:element>
        <xs:element name="payback" maxOccurs="unbounded" minOccurs="0">
          <xs:annotation>
            <xs:documentation> Scroll: Boost Attack (Time-limited) Sealed вЂ” 5 pcs.  Scroll: Boost Attack (Time-limited) Sealed вЂ” 5 pcs.  Scroll: Boost Defense (Time-limited) Sealed вЂ” 10 pcs.  Charging Stone of Random Craft - 1 Charge (Time-limited) Sealed вЂ” 1 pc.  Charging Stone of Random Craft - 1 Charge (Time-limited) Sealed вЂ” 2 pc.  Elixir Powder Sealed вЂ” 1 pc.  Scroll of Blessing Sealed вЂ” 1 pc. </xs:documentation>
          </xs:annotation>
          <xs:complexType>
            <xs:sequence>
              <xs:element name="item" maxOccurs="unbounded" minOccurs="0">
                <xs:annotation>
                  <xs:documentation> Scroll: Boost Attack (Time-limited) Sealed вЂ” 5 pcs.  Scroll: Boost Defense (Time-limited) Sealed вЂ” 5 pcs. </xs:documentation>
                </xs:annotation>
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute type="xs:int" name="id" use="optional"/>
                      <xs:attribute type="xs:byte" name="count" use="optional"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute type="xs:byte" name="id" use="optional"/>
            <xs:attribute type="xs:short" name="count" use="optional"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== fermatupotop/L2J_Mobius_Essence_6.2_Vanguard/game/data/scripts_waytrel/events/GoldenWheel/rewards.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="rewards.xsd">
    <params minLevel="1" maxLevel="-1" coinId="94834"/> <!-- maxLevel -1 - no limit -->
    <multisells>3247847</multisells>
    <payback id="1" count="100">
        <item id="94269" count="10"/>
        <item id="94271" count="10"/> 
        <item id="49674" count="10"/> 
    </payback>
    <payback id="2" count="300">
        <item id="91757" count="5"/> 
        <item id="91712" count="5"/> 
        <item id="97145" count="30"/> 
    </payback>
    <payback id="3" count="500">
        <item id="96941" count="1"/> 
        <item id="91712" count="10"/>
        <item id="92020" count="2"/> 
    </payback>
    <payback id="4" count="700">
        <item id="94269" count="15"/>
        <item id="94271" count="15"/> 
        <item id="49674" count="15"/> 
    </payback>
    <payback id="5" count="1000">
        <item id="97145" count="50"/>
        <item id="97266" count="2"/> 
        <item id="49845" count="100"/>
    </payback>
    <payback id="6" count="1500">
        <item id="94269" count="25"/>
        <item id="94271" count="25"/>
        <item id="49674" count="25"/> 
    </payback>
    <payback id="7" count="2000">
        <item id="97145" count="100"/> 
        <item id="91712" count="20"/> 
        <item id="91757" count="20"/>
    </payback>
</list>
